name: Deploy to WordPress.org
on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SVN
      run: sudo apt-get install -y subversion

    - name: Publish to SVN
      run: |
        # Export Git tag to SVN tag
        mkdir ./svn
        svn checkout --depth immediates "https://plugins.svn.wordpress.org/minimal-maintenance-mode" ./svn
        svn update --set-depth infinity ./svn/tags/$GITHUB_REF

        # Move assets, trunk, and tag
        rsync -a --exclude=".svn" ./assets/ ./svn/assets/
        rsync -a --exclude=".svn" ./trunk/ ./svn/trunk/
        rsync -a --exclude=".svn" ./tags/$GITHUB_REF/ ./svn/tags/$GITHUB_REF/

        # SVN commit
        cd ./svn
        svn add --force * --auto-props --parents --depth infinity -q
        svn commit -m "Release $GITHUB_REF, build $GITHUB_RUN_ID" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
